/**
 * PhishForensics AI - Threat Analysis Input Contract
 * 
 * Defines the contract for dynamic findings ingested from upstream AI Threat Analysis (Member 1).
 * The schema is intentionally extensible and does not prescribe a fixed or rigid list of phishing techniques.
 */

/**
 * Attacker intent identified by dynamic AI analysis.
 */
export interface AttackerIntent {
  /** High-level primary goal (e.g. credential theft, financial fraud, malware delivery, reconnaissance) */
  primaryGoal: string;
  /** In-depth contextual narrative of what the attacker seeks to achieve */
  description: string;
  /** Qualitative confidence indicator (e.g. "low", "medium", "high", "verified") */
  confidence?: string;
  /** Extensible secondary or opportunistic goals identified by AI */
  secondaryGoals?: string[];
}

/**
 * Technical, syntactic, or contextual indicator identified in the analyzed content.
 */
export interface ThreatIndicator {
  /** Indicator category (e.g. "suspicious_domain", "sender_spoof", "urgency_cue", "hidden_redirect", "brand_lookalike") */
  type: string;
  /** The specific observed indicator value or behavior */
  value: string;
  /** Where in the artifact this indicator appeared (e.g. "Header:From", "Body:Link", "Attachment:Filename") */
  context?: string;
  /** Qualitative severity indicator (e.g. "informational", "low", "medium", "high", "critical") */
  severity?: string;
  /** Supporting notes or explanation generated by AI analysis */
  explanation?: string;
}

/**
 * Social engineering and psychological manipulation techniques identified in the lure.
 */
export interface ManipulationTechnique {
  /** Name of the technique (e.g. "Authority Pretext", "Manufactured Scarcity", "Fear Appeal") */
  name: string;
  /** Broad category (e.g. "psychological", "deception", "social_engineering", "technical") */
  category?: string;
  /** Contextual explanation of how this technique is deployed in the specific attack */
  description: string;
  /** Specific quote, sentence, or artifact fragment manifesting this technique */
  evidenceSnippet?: string;
}

/**
 * Grounded piece of evidence extracted during threat analysis.
 */
export interface EvidenceItem {
  /** Unique identifier for cross-referencing in reconstruction */
  id: string;
  /** Artifact domain (e.g. "header", "body", "link", "attachment", "metadata") */
  type: string;
  /** Concrete analytical finding */
  finding: string;
  /** Raw text or data fragment supporting the finding */
  rawSnippet?: string;
  /** Optional metadata tags associated with this evidence */
  tags?: string[];
}

/**
 * Qualitative risk evaluation produced by AI threat analysis.
 */
export interface RiskInformation {
  /** Qualitative risk tier (e.g. "low", "medium", "high", "critical") - non-hardcoded string */
  level: string;
  /** Analytical justification for the risk evaluation */
  assessment: string;
  /** Specific assets, data, or individuals vulnerable if targeted */
  potentialImpact: string[];
  /** Dynamic context-dependent risk factors */
  additionalFactors?: Record<string, unknown>;
}

/**
 * Real-world or digital entities identified within the threat content.
 */
export interface ExtractedEntity {
  /** Entity classification (e.g. "brand", "domain", "email_address", "organization", "person", "file") */
  entityType: string;
  /** Name, identifier, or string representation of the entity */
  name: string;
  /** Role in the threat scenario (e.g. "impersonated_target", "sender", "redirect_target", "recipient") */
  role: string;
  /** Extensible entity-specific metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Top-level contract for dynamic threat analysis findings passed to Attack Reconstruction.
 */
export interface ThreatAnalysisInput {
  /** Unique reference identifier for the analysis session */
  analysisId?: string;
  /** ISO-8601 timestamp of analysis generation */
  analyzedAt?: string;
  /** Medium of the suspicious content (e.g. "email", "url", "sms", "qr_code", "document") */
  sourceType: string;
  /** Dynamic attacker intent */
  attackerIntent: AttackerIntent;
  /** Extensible array of observed threat indicators */
  indicators: ThreatIndicator[];
  /** Extensible array of social engineering manipulation techniques */
  manipulationTechniques: ManipulationTechnique[];
  /** Grounded analytical evidence items */
  evidence: EvidenceItem[];
  /** Qualitative risk evaluation */
  riskInformation: RiskInformation;
  /** Identified entities and their roles in the attack */
  entities: ExtractedEntity[];
  /** Open metadata bag for future AI analytical extensions */
  metadata?: Record<string, unknown>;
}
